# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 4
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.cache/wt [current_project]
set_property parent.project_path /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /scratch/local/tmp.tEdaivbEa4/_sds/iprepo/repo
  /mnt/icgridio2/safe/SDSoC/SDx/2017.1/data/ip/xilinx
  /mnt/icgridio2/safe/SDSoC/SDx/2017.1/data/cache/xilinx
} [current_project]
set_property ip_output_repo /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/hdl/pynq_wrapper.vhd
add_files /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/pynq.bd
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_0_0/pynq_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_0_0/pynq_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_0_0/pynq_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_1_0/pynq_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_1_0/pynq_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_1_0/pynq_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_2_0/pynq_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_2_0/pynq_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_2_0/pynq_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_3_0/pynq_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_3_0/pynq_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_proc_sys_reset_3_0/pynq_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_dm_0_0/pynq_dm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_dm_0_0/pynq_dm_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_dm_0_0/pynq_dm_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_encrypt_1_0/constraints/a0_encrypt_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_xbar_1/pynq_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_xbar_0/pynq_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_m00_data_fifo_0/pynq_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_m00_regslice_1/pynq_m00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_pc_2/pynq_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s03_regslice_0/pynq_s03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s03_data_fifo_0/pynq_s03_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s02_regslice_0/pynq_s02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_3/pynq_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_3/pynq_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_3/pynq_auto_us_df_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s01_regslice_0/pynq_s01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_2/pynq_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_2/pynq_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_2/pynq_auto_us_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_2/pynq_s00_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_1/pynq_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_1/pynq_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_1/pynq_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_0/pynq_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_0/pynq_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_us_df_0/pynq_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_m01_regslice_0/pynq_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_m00_regslice_0/pynq_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_0/pynq_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_data_fifo_0/pynq_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/pynq_ooc.xdc]
set_property is_locked true [get_files /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/pynq.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pynq_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef pynq_wrapper.dcp

catch { report_utilization -file pynq_wrapper_utilization_synth.rpt -pb pynq_wrapper_utilization_synth.pb }
