# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynq/pynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq || ORIG_REF_NAME==pynq}]

# IP: bd/pynq/ip/pynq_proc_sys_reset_0_0/pynq_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_proc_sys_reset_0_0 || ORIG_REF_NAME==pynq_proc_sys_reset_0_0}]

# IP: bd/pynq/ip/pynq_proc_sys_reset_1_0/pynq_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_proc_sys_reset_1_0 || ORIG_REF_NAME==pynq_proc_sys_reset_1_0}]

# IP: bd/pynq/ip/pynq_proc_sys_reset_2_0/pynq_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_proc_sys_reset_2_0 || ORIG_REF_NAME==pynq_proc_sys_reset_2_0}]

# IP: bd/pynq/ip/pynq_proc_sys_reset_3_0/pynq_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_proc_sys_reset_3_0 || ORIG_REF_NAME==pynq_proc_sys_reset_3_0}]

# IP: bd/pynq/ip/pynq_processing_system7_0_0/pynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_processing_system7_0_0 || ORIG_REF_NAME==pynq_processing_system7_0_0}]

# IP: bd/pynq/ip/pynq_xlconcat_0_0/pynq_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_xlconcat_0_0 || ORIG_REF_NAME==pynq_xlconcat_0_0}]

# IP: bd/pynq/ip/pynq_dm_0_0/pynq_dm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_dm_0_0 || ORIG_REF_NAME==pynq_dm_0_0}]

# IP: bd/pynq/ip/pynq_encrypt_1_0/pynq_encrypt_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_encrypt_1_0 || ORIG_REF_NAME==pynq_encrypt_1_0}]

# IP: bd/pynq/ip/pynq_encrypt_1_if_0/pynq_encrypt_1_if_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_encrypt_1_if_0 || ORIG_REF_NAME==pynq_encrypt_1_if_0}]

# IP: bd/pynq/ip/pynq_axi_ic_processing_system7_0_M_AXI_GP0_0/pynq_axi_ic_processing_system7_0_M_AXI_GP0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_axi_ic_processing_system7_0_M_AXI_GP0_0 || ORIG_REF_NAME==pynq_axi_ic_processing_system7_0_M_AXI_GP0_0}]

# IP: bd/pynq/ip/pynq_axi_ic_processing_system7_0_S_AXI_ACP_0/pynq_axi_ic_processing_system7_0_S_AXI_ACP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_axi_ic_processing_system7_0_S_AXI_ACP_0 || ORIG_REF_NAME==pynq_axi_ic_processing_system7_0_S_AXI_ACP_0}]

# IP: bd/pynq/ip/pynq_sds_irq_const_0/pynq_sds_irq_const_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_sds_irq_const_0 || ORIG_REF_NAME==pynq_sds_irq_const_0}]

# IP: bd/pynq/ip/pynq_axcache_0xE_0/pynq_axcache_0xE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_axcache_0xE_0 || ORIG_REF_NAME==pynq_axcache_0xE_0}]

# IP: bd/pynq/ip/pynq_xbar_1/pynq_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_xbar_1 || ORIG_REF_NAME==pynq_xbar_1}]

# IP: bd/pynq/ip/pynq_xbar_0/pynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_xbar_0 || ORIG_REF_NAME==pynq_xbar_0}]

# IP: bd/pynq/ip/pynq_m00_data_fifo_0/pynq_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_m00_data_fifo_0 || ORIG_REF_NAME==pynq_m00_data_fifo_0}]

# IP: bd/pynq/ip/pynq_m00_regslice_1/pynq_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_m00_regslice_1 || ORIG_REF_NAME==pynq_m00_regslice_1}]

# IP: bd/pynq/ip/pynq_auto_ds_0/pynq_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_ds_0 || ORIG_REF_NAME==pynq_auto_ds_0}]

# IP: bd/pynq/ip/pynq_auto_pc_1/pynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_pc_1 || ORIG_REF_NAME==pynq_auto_pc_1}]

# IP: bd/pynq/ip/pynq_s02_regslice_0/pynq_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s02_regslice_0 || ORIG_REF_NAME==pynq_s02_regslice_0}]

# IP: bd/pynq/ip/pynq_auto_us_df_0/pynq_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_us_df_0 || ORIG_REF_NAME==pynq_auto_us_df_0}]

# IP: bd/pynq/ip/pynq_s01_regslice_0/pynq_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s01_regslice_0 || ORIG_REF_NAME==pynq_s01_regslice_0}]

# IP: bd/pynq/ip/pynq_auto_us_cc_df_0/pynq_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_us_cc_df_0 || ORIG_REF_NAME==pynq_auto_us_cc_df_0}]

# IP: bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s00_regslice_1 || ORIG_REF_NAME==pynq_s00_regslice_1}]

# IP: bd/pynq/ip/pynq_s00_data_fifo_1/pynq_s00_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s00_data_fifo_1 || ORIG_REF_NAME==pynq_s00_data_fifo_1}]

# IP: bd/pynq/ip/pynq_auto_cc_0/pynq_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_cc_0 || ORIG_REF_NAME==pynq_auto_cc_0}]

# IP: bd/pynq/ip/pynq_m01_regslice_0/pynq_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_m01_regslice_0 || ORIG_REF_NAME==pynq_m01_regslice_0}]

# IP: bd/pynq/ip/pynq_m00_regslice_0/pynq_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_m00_regslice_0 || ORIG_REF_NAME==pynq_m00_regslice_0}]

# IP: bd/pynq/ip/pynq_s00_regslice_0/pynq_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s00_regslice_0 || ORIG_REF_NAME==pynq_s00_regslice_0}]

# IP: bd/pynq/ip/pynq_s00_data_fifo_0/pynq_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_s00_data_fifo_0 || ORIG_REF_NAME==pynq_s00_data_fifo_0}]

# IP: bd/pynq/ip/pynq_auto_pc_0/pynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynq_auto_pc_0 || ORIG_REF_NAME==pynq_auto_pc_0}]

# XDC: bd/pynq/pynq_ooc.xdc
