// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_aes_addRoundKey.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_aes_addRoundKey::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic a0_aes_addRoundKey::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state1 = "1";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state2 = "10";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state3 = "100";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state4 = "1000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state5 = "10000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state6 = "100000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> a0_aes_addRoundKey::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> a0_aes_addRoundKey::ap_const_lv1_0 = "0";
const sc_lv<3> a0_aes_addRoundKey::ap_const_lv3_0 = "000";
const sc_lv<2> a0_aes_addRoundKey::ap_const_lv2_0 = "00";
const sc_lv<4> a0_aes_addRoundKey::ap_const_lv4_0 = "0000";
const sc_lv<8> a0_aes_addRoundKey::ap_const_lv8_0 = "00000000";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_3 = "11";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_A = "1010";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_B = "1011";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_C = "1100";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_11 = "10001";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_1 = "1";
const sc_lv<32> a0_aes_addRoundKey::ap_const_lv32_2 = "10";
const sc_lv<5> a0_aes_addRoundKey::ap_const_lv5_10 = "10000";
const bool a0_aes_addRoundKey::ap_const_boolean_0 = false;
const sc_lv<1> a0_aes_addRoundKey::ap_const_lv1_1 = "1";
const sc_lv<5> a0_aes_addRoundKey::ap_const_lv5_1F = "11111";
const sc_lv<5> a0_aes_addRoundKey::ap_const_lv5_0 = "00000";
const bool a0_aes_addRoundKey::ap_const_boolean_1 = true;

a0_aes_addRoundKey::a0_aes_addRoundKey(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state11);
    sensitive << ( m_axi_buf_r_RVALID );
    sensitive << ( m_axi_key_RVALID );

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( ap_sig_ioackin_m_axi_key_ARREADY );
    sensitive << ( ap_sig_ioackin_m_axi_buf_r_ARREADY );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_135_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_135_p2 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_buf_r_ARREADY);
    sensitive << ( m_axi_buf_r_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_ARREADY );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_buf_r_AWREADY);
    sensitive << ( m_axi_buf_r_AWREADY );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_buf_r_WREADY);
    sensitive << ( m_axi_buf_r_WREADY );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_WREADY );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_key_ARREADY);
    sensitive << ( m_axi_key_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_key_ARREADY );

    SC_METHOD(thread_buf_r_blk_n_AR);
    sensitive << ( m_axi_buf_r_ARREADY );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_buf_r_blk_n_AW);
    sensitive << ( m_axi_buf_r_AWREADY );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_buf_r_blk_n_B);
    sensitive << ( m_axi_buf_r_BVALID );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_buf_r_blk_n_R);
    sensitive << ( m_axi_buf_r_RVALID );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_buf_r_blk_n_W);
    sensitive << ( m_axi_buf_r_WREADY );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_i_11_cast_fu_131_p1);
    sensitive << ( i_11_fu_125_p2 );

    SC_METHOD(thread_i_11_fu_125_p2);
    sensitive << ( i_reg_110 );

    SC_METHOD(thread_key_blk_n_AR);
    sensitive << ( m_axi_key_ARREADY );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_key_blk_n_R);
    sensitive << ( m_axi_key_RVALID );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_m_axi_buf_r_ARADDR);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( buf_addr_reg_207 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_ARREADY );

    SC_METHOD(thread_m_axi_buf_r_ARBURST);

    SC_METHOD(thread_m_axi_buf_r_ARCACHE);

    SC_METHOD(thread_m_axi_buf_r_ARID);

    SC_METHOD(thread_m_axi_buf_r_ARLEN);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_ARREADY );

    SC_METHOD(thread_m_axi_buf_r_ARLOCK);

    SC_METHOD(thread_m_axi_buf_r_ARPROT);

    SC_METHOD(thread_m_axi_buf_r_ARQOS);

    SC_METHOD(thread_m_axi_buf_r_ARREGION);

    SC_METHOD(thread_m_axi_buf_r_ARSIZE);

    SC_METHOD(thread_m_axi_buf_r_ARUSER);

    SC_METHOD(thread_m_axi_buf_r_ARVALID);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_ARREADY );

    SC_METHOD(thread_m_axi_buf_r_AWADDR);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( buf_addr_reg_207 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_AWREADY );

    SC_METHOD(thread_m_axi_buf_r_AWBURST);

    SC_METHOD(thread_m_axi_buf_r_AWCACHE);

    SC_METHOD(thread_m_axi_buf_r_AWID);

    SC_METHOD(thread_m_axi_buf_r_AWLEN);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_AWREADY );

    SC_METHOD(thread_m_axi_buf_r_AWLOCK);

    SC_METHOD(thread_m_axi_buf_r_AWPROT);

    SC_METHOD(thread_m_axi_buf_r_AWQOS);

    SC_METHOD(thread_m_axi_buf_r_AWREGION);

    SC_METHOD(thread_m_axi_buf_r_AWSIZE);

    SC_METHOD(thread_m_axi_buf_r_AWUSER);

    SC_METHOD(thread_m_axi_buf_r_AWVALID);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_AWREADY );

    SC_METHOD(thread_m_axi_buf_r_BREADY);
    sensitive << ( m_axi_buf_r_BVALID );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_m_axi_buf_r_RREADY);
    sensitive << ( m_axi_buf_r_RVALID );
    sensitive << ( m_axi_key_RVALID );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_m_axi_buf_r_WDATA);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_34_reg_230 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_WREADY );

    SC_METHOD(thread_m_axi_buf_r_WID);

    SC_METHOD(thread_m_axi_buf_r_WLAST);

    SC_METHOD(thread_m_axi_buf_r_WSTRB);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_WREADY );

    SC_METHOD(thread_m_axi_buf_r_WUSER);

    SC_METHOD(thread_m_axi_buf_r_WVALID);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_reg_ioackin_m_axi_buf_r_WREADY );

    SC_METHOD(thread_m_axi_key_ARADDR);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( key_addr_reg_214 );
    sensitive << ( ap_reg_ioackin_m_axi_key_ARREADY );

    SC_METHOD(thread_m_axi_key_ARBURST);

    SC_METHOD(thread_m_axi_key_ARCACHE);

    SC_METHOD(thread_m_axi_key_ARID);

    SC_METHOD(thread_m_axi_key_ARLEN);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_reg_ioackin_m_axi_key_ARREADY );

    SC_METHOD(thread_m_axi_key_ARLOCK);

    SC_METHOD(thread_m_axi_key_ARPROT);

    SC_METHOD(thread_m_axi_key_ARQOS);

    SC_METHOD(thread_m_axi_key_ARREGION);

    SC_METHOD(thread_m_axi_key_ARSIZE);

    SC_METHOD(thread_m_axi_key_ARUSER);

    SC_METHOD(thread_m_axi_key_ARVALID);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_reg_ioackin_m_axi_key_ARREADY );

    SC_METHOD(thread_m_axi_key_AWADDR);

    SC_METHOD(thread_m_axi_key_AWBURST);

    SC_METHOD(thread_m_axi_key_AWCACHE);

    SC_METHOD(thread_m_axi_key_AWID);

    SC_METHOD(thread_m_axi_key_AWLEN);

    SC_METHOD(thread_m_axi_key_AWLOCK);

    SC_METHOD(thread_m_axi_key_AWPROT);

    SC_METHOD(thread_m_axi_key_AWQOS);

    SC_METHOD(thread_m_axi_key_AWREGION);

    SC_METHOD(thread_m_axi_key_AWSIZE);

    SC_METHOD(thread_m_axi_key_AWUSER);

    SC_METHOD(thread_m_axi_key_AWVALID);

    SC_METHOD(thread_m_axi_key_BREADY);

    SC_METHOD(thread_m_axi_key_RREADY);
    sensitive << ( m_axi_buf_r_RVALID );
    sensitive << ( m_axi_key_RVALID );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_m_axi_key_WDATA);

    SC_METHOD(thread_m_axi_key_WID);

    SC_METHOD(thread_m_axi_key_WLAST);

    SC_METHOD(thread_m_axi_key_WSTRB);

    SC_METHOD(thread_m_axi_key_WUSER);

    SC_METHOD(thread_m_axi_key_WVALID);

    SC_METHOD(thread_sum1_fu_150_p2);
    sensitive << ( buf_offset );
    sensitive << ( tmp_s_fu_141_p1 );

    SC_METHOD(thread_sum3_fu_164_p2);
    sensitive << ( key_offset );
    sensitive << ( sum_cast_fu_161_p1 );

    SC_METHOD(thread_sum_cast_fu_161_p1);
    sensitive << ( sum_reg_202 );

    SC_METHOD(thread_sum_fu_145_p2);
    sensitive << ( tmp_42_reg_189 );
    sensitive << ( i_11_fu_125_p2 );

    SC_METHOD(thread_tmp_34_fu_175_p2);
    sensitive << ( key_addr_read_reg_220 );
    sensitive << ( buf_addr_read_reg_225 );

    SC_METHOD(thread_tmp_42_fu_121_p1);
    sensitive << ( key_offset_offset );

    SC_METHOD(thread_tmp_fu_135_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_110 );

    SC_METHOD(thread_tmp_s_fu_141_p1);
    sensitive << ( i_11_cast_fu_131_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_buf_r_RVALID );
    sensitive << ( m_axi_buf_r_BVALID );
    sensitive << ( m_axi_key_RVALID );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_135_p2 );
    sensitive << ( ap_sig_ioackin_m_axi_buf_r_AWREADY );
    sensitive << ( ap_block_state4_io );
    sensitive << ( ap_sig_ioackin_m_axi_buf_r_WREADY );

    ap_CS_fsm = "000000000000000001";
    ap_reg_ioackin_m_axi_key_ARREADY = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_buf_r_ARREADY = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_buf_r_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_buf_r_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_aes_addRoundKey_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_buf_r_AWVALID, "(port)m_axi_buf_r_AWVALID");
    sc_trace(mVcdFile, m_axi_buf_r_AWREADY, "(port)m_axi_buf_r_AWREADY");
    sc_trace(mVcdFile, m_axi_buf_r_AWADDR, "(port)m_axi_buf_r_AWADDR");
    sc_trace(mVcdFile, m_axi_buf_r_AWID, "(port)m_axi_buf_r_AWID");
    sc_trace(mVcdFile, m_axi_buf_r_AWLEN, "(port)m_axi_buf_r_AWLEN");
    sc_trace(mVcdFile, m_axi_buf_r_AWSIZE, "(port)m_axi_buf_r_AWSIZE");
    sc_trace(mVcdFile, m_axi_buf_r_AWBURST, "(port)m_axi_buf_r_AWBURST");
    sc_trace(mVcdFile, m_axi_buf_r_AWLOCK, "(port)m_axi_buf_r_AWLOCK");
    sc_trace(mVcdFile, m_axi_buf_r_AWCACHE, "(port)m_axi_buf_r_AWCACHE");
    sc_trace(mVcdFile, m_axi_buf_r_AWPROT, "(port)m_axi_buf_r_AWPROT");
    sc_trace(mVcdFile, m_axi_buf_r_AWQOS, "(port)m_axi_buf_r_AWQOS");
    sc_trace(mVcdFile, m_axi_buf_r_AWREGION, "(port)m_axi_buf_r_AWREGION");
    sc_trace(mVcdFile, m_axi_buf_r_AWUSER, "(port)m_axi_buf_r_AWUSER");
    sc_trace(mVcdFile, m_axi_buf_r_WVALID, "(port)m_axi_buf_r_WVALID");
    sc_trace(mVcdFile, m_axi_buf_r_WREADY, "(port)m_axi_buf_r_WREADY");
    sc_trace(mVcdFile, m_axi_buf_r_WDATA, "(port)m_axi_buf_r_WDATA");
    sc_trace(mVcdFile, m_axi_buf_r_WSTRB, "(port)m_axi_buf_r_WSTRB");
    sc_trace(mVcdFile, m_axi_buf_r_WLAST, "(port)m_axi_buf_r_WLAST");
    sc_trace(mVcdFile, m_axi_buf_r_WID, "(port)m_axi_buf_r_WID");
    sc_trace(mVcdFile, m_axi_buf_r_WUSER, "(port)m_axi_buf_r_WUSER");
    sc_trace(mVcdFile, m_axi_buf_r_ARVALID, "(port)m_axi_buf_r_ARVALID");
    sc_trace(mVcdFile, m_axi_buf_r_ARREADY, "(port)m_axi_buf_r_ARREADY");
    sc_trace(mVcdFile, m_axi_buf_r_ARADDR, "(port)m_axi_buf_r_ARADDR");
    sc_trace(mVcdFile, m_axi_buf_r_ARID, "(port)m_axi_buf_r_ARID");
    sc_trace(mVcdFile, m_axi_buf_r_ARLEN, "(port)m_axi_buf_r_ARLEN");
    sc_trace(mVcdFile, m_axi_buf_r_ARSIZE, "(port)m_axi_buf_r_ARSIZE");
    sc_trace(mVcdFile, m_axi_buf_r_ARBURST, "(port)m_axi_buf_r_ARBURST");
    sc_trace(mVcdFile, m_axi_buf_r_ARLOCK, "(port)m_axi_buf_r_ARLOCK");
    sc_trace(mVcdFile, m_axi_buf_r_ARCACHE, "(port)m_axi_buf_r_ARCACHE");
    sc_trace(mVcdFile, m_axi_buf_r_ARPROT, "(port)m_axi_buf_r_ARPROT");
    sc_trace(mVcdFile, m_axi_buf_r_ARQOS, "(port)m_axi_buf_r_ARQOS");
    sc_trace(mVcdFile, m_axi_buf_r_ARREGION, "(port)m_axi_buf_r_ARREGION");
    sc_trace(mVcdFile, m_axi_buf_r_ARUSER, "(port)m_axi_buf_r_ARUSER");
    sc_trace(mVcdFile, m_axi_buf_r_RVALID, "(port)m_axi_buf_r_RVALID");
    sc_trace(mVcdFile, m_axi_buf_r_RREADY, "(port)m_axi_buf_r_RREADY");
    sc_trace(mVcdFile, m_axi_buf_r_RDATA, "(port)m_axi_buf_r_RDATA");
    sc_trace(mVcdFile, m_axi_buf_r_RLAST, "(port)m_axi_buf_r_RLAST");
    sc_trace(mVcdFile, m_axi_buf_r_RID, "(port)m_axi_buf_r_RID");
    sc_trace(mVcdFile, m_axi_buf_r_RUSER, "(port)m_axi_buf_r_RUSER");
    sc_trace(mVcdFile, m_axi_buf_r_RRESP, "(port)m_axi_buf_r_RRESP");
    sc_trace(mVcdFile, m_axi_buf_r_BVALID, "(port)m_axi_buf_r_BVALID");
    sc_trace(mVcdFile, m_axi_buf_r_BREADY, "(port)m_axi_buf_r_BREADY");
    sc_trace(mVcdFile, m_axi_buf_r_BRESP, "(port)m_axi_buf_r_BRESP");
    sc_trace(mVcdFile, m_axi_buf_r_BID, "(port)m_axi_buf_r_BID");
    sc_trace(mVcdFile, m_axi_buf_r_BUSER, "(port)m_axi_buf_r_BUSER");
    sc_trace(mVcdFile, buf_offset, "(port)buf_offset");
    sc_trace(mVcdFile, m_axi_key_AWVALID, "(port)m_axi_key_AWVALID");
    sc_trace(mVcdFile, m_axi_key_AWREADY, "(port)m_axi_key_AWREADY");
    sc_trace(mVcdFile, m_axi_key_AWADDR, "(port)m_axi_key_AWADDR");
    sc_trace(mVcdFile, m_axi_key_AWID, "(port)m_axi_key_AWID");
    sc_trace(mVcdFile, m_axi_key_AWLEN, "(port)m_axi_key_AWLEN");
    sc_trace(mVcdFile, m_axi_key_AWSIZE, "(port)m_axi_key_AWSIZE");
    sc_trace(mVcdFile, m_axi_key_AWBURST, "(port)m_axi_key_AWBURST");
    sc_trace(mVcdFile, m_axi_key_AWLOCK, "(port)m_axi_key_AWLOCK");
    sc_trace(mVcdFile, m_axi_key_AWCACHE, "(port)m_axi_key_AWCACHE");
    sc_trace(mVcdFile, m_axi_key_AWPROT, "(port)m_axi_key_AWPROT");
    sc_trace(mVcdFile, m_axi_key_AWQOS, "(port)m_axi_key_AWQOS");
    sc_trace(mVcdFile, m_axi_key_AWREGION, "(port)m_axi_key_AWREGION");
    sc_trace(mVcdFile, m_axi_key_AWUSER, "(port)m_axi_key_AWUSER");
    sc_trace(mVcdFile, m_axi_key_WVALID, "(port)m_axi_key_WVALID");
    sc_trace(mVcdFile, m_axi_key_WREADY, "(port)m_axi_key_WREADY");
    sc_trace(mVcdFile, m_axi_key_WDATA, "(port)m_axi_key_WDATA");
    sc_trace(mVcdFile, m_axi_key_WSTRB, "(port)m_axi_key_WSTRB");
    sc_trace(mVcdFile, m_axi_key_WLAST, "(port)m_axi_key_WLAST");
    sc_trace(mVcdFile, m_axi_key_WID, "(port)m_axi_key_WID");
    sc_trace(mVcdFile, m_axi_key_WUSER, "(port)m_axi_key_WUSER");
    sc_trace(mVcdFile, m_axi_key_ARVALID, "(port)m_axi_key_ARVALID");
    sc_trace(mVcdFile, m_axi_key_ARREADY, "(port)m_axi_key_ARREADY");
    sc_trace(mVcdFile, m_axi_key_ARADDR, "(port)m_axi_key_ARADDR");
    sc_trace(mVcdFile, m_axi_key_ARID, "(port)m_axi_key_ARID");
    sc_trace(mVcdFile, m_axi_key_ARLEN, "(port)m_axi_key_ARLEN");
    sc_trace(mVcdFile, m_axi_key_ARSIZE, "(port)m_axi_key_ARSIZE");
    sc_trace(mVcdFile, m_axi_key_ARBURST, "(port)m_axi_key_ARBURST");
    sc_trace(mVcdFile, m_axi_key_ARLOCK, "(port)m_axi_key_ARLOCK");
    sc_trace(mVcdFile, m_axi_key_ARCACHE, "(port)m_axi_key_ARCACHE");
    sc_trace(mVcdFile, m_axi_key_ARPROT, "(port)m_axi_key_ARPROT");
    sc_trace(mVcdFile, m_axi_key_ARQOS, "(port)m_axi_key_ARQOS");
    sc_trace(mVcdFile, m_axi_key_ARREGION, "(port)m_axi_key_ARREGION");
    sc_trace(mVcdFile, m_axi_key_ARUSER, "(port)m_axi_key_ARUSER");
    sc_trace(mVcdFile, m_axi_key_RVALID, "(port)m_axi_key_RVALID");
    sc_trace(mVcdFile, m_axi_key_RREADY, "(port)m_axi_key_RREADY");
    sc_trace(mVcdFile, m_axi_key_RDATA, "(port)m_axi_key_RDATA");
    sc_trace(mVcdFile, m_axi_key_RLAST, "(port)m_axi_key_RLAST");
    sc_trace(mVcdFile, m_axi_key_RID, "(port)m_axi_key_RID");
    sc_trace(mVcdFile, m_axi_key_RUSER, "(port)m_axi_key_RUSER");
    sc_trace(mVcdFile, m_axi_key_RRESP, "(port)m_axi_key_RRESP");
    sc_trace(mVcdFile, m_axi_key_BVALID, "(port)m_axi_key_BVALID");
    sc_trace(mVcdFile, m_axi_key_BREADY, "(port)m_axi_key_BREADY");
    sc_trace(mVcdFile, m_axi_key_BRESP, "(port)m_axi_key_BRESP");
    sc_trace(mVcdFile, m_axi_key_BID, "(port)m_axi_key_BID");
    sc_trace(mVcdFile, m_axi_key_BUSER, "(port)m_axi_key_BUSER");
    sc_trace(mVcdFile, key_offset, "(port)key_offset");
    sc_trace(mVcdFile, key_offset_offset, "(port)key_offset_offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, buf_r_blk_n_AR, "buf_r_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, buf_r_blk_n_R, "buf_r_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, buf_r_blk_n_AW, "buf_r_blk_n_AW");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, buf_r_blk_n_W, "buf_r_blk_n_W");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, buf_r_blk_n_B, "buf_r_blk_n_B");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, key_blk_n_AR, "key_blk_n_AR");
    sc_trace(mVcdFile, key_blk_n_R, "key_blk_n_R");
    sc_trace(mVcdFile, tmp_42_fu_121_p1, "tmp_42_fu_121_p1");
    sc_trace(mVcdFile, tmp_42_reg_189, "tmp_42_reg_189");
    sc_trace(mVcdFile, i_11_fu_125_p2, "i_11_fu_125_p2");
    sc_trace(mVcdFile, i_11_reg_194, "i_11_reg_194");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sum_fu_145_p2, "sum_fu_145_p2");
    sc_trace(mVcdFile, sum_reg_202, "sum_reg_202");
    sc_trace(mVcdFile, tmp_fu_135_p2, "tmp_fu_135_p2");
    sc_trace(mVcdFile, buf_addr_reg_207, "buf_addr_reg_207");
    sc_trace(mVcdFile, key_addr_reg_214, "key_addr_reg_214");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, key_addr_read_reg_220, "key_addr_read_reg_220");
    sc_trace(mVcdFile, ap_block_state11, "ap_block_state11");
    sc_trace(mVcdFile, buf_addr_read_reg_225, "buf_addr_read_reg_225");
    sc_trace(mVcdFile, tmp_34_fu_175_p2, "tmp_34_fu_175_p2");
    sc_trace(mVcdFile, tmp_34_reg_230, "tmp_34_reg_230");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_buf_r_AWREADY, "ap_sig_ioackin_m_axi_buf_r_AWREADY");
    sc_trace(mVcdFile, i_reg_110, "i_reg_110");
    sc_trace(mVcdFile, sum1_fu_150_p2, "sum1_fu_150_p2");
    sc_trace(mVcdFile, sum3_fu_164_p2, "sum3_fu_164_p2");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_key_ARREADY, "ap_reg_ioackin_m_axi_key_ARREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_key_ARREADY, "ap_sig_ioackin_m_axi_key_ARREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_buf_r_ARREADY, "ap_sig_ioackin_m_axi_buf_r_ARREADY");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_buf_r_ARREADY, "ap_reg_ioackin_m_axi_buf_r_ARREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_buf_r_AWREADY, "ap_reg_ioackin_m_axi_buf_r_AWREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_buf_r_WREADY, "ap_reg_ioackin_m_axi_buf_r_WREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_buf_r_WREADY, "ap_sig_ioackin_m_axi_buf_r_WREADY");
    sc_trace(mVcdFile, i_11_cast_fu_131_p1, "i_11_cast_fu_131_p1");
    sc_trace(mVcdFile, tmp_s_fu_141_p1, "tmp_s_fu_141_p1");
    sc_trace(mVcdFile, sum_cast_fu_161_p1, "sum_cast_fu_161_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

a0_aes_addRoundKey::~a0_aes_addRoundKey() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void a0_aes_addRoundKey::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_buf_r_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            if (esl_seteq<1,1,1>(ap_block_state4_io.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_m_axi_buf_r_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_buf_r_ARREADY.read())) {
                ap_reg_ioackin_m_axi_buf_r_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_buf_r_AWREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_buf_r_AWREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_m_axi_buf_r_AWREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_buf_r_AWREADY.read())) {
                ap_reg_ioackin_m_axi_buf_r_AWREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_buf_r_WREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_buf_r_WREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_m_axi_buf_r_WREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_buf_r_WREADY.read())) {
                ap_reg_ioackin_m_axi_buf_r_WREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_key_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            if (esl_seteq<1,1,1>(ap_block_state4_io.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_m_axi_key_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_key_ARREADY.read())) {
                ap_reg_ioackin_m_axi_key_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
         esl_seteq<1,1,1>(m_axi_buf_r_BVALID.read(), ap_const_logic_1))) {
        i_reg_110 = i_11_reg_194.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_110 = ap_const_lv5_10;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, m_axi_key_RVALID.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_buf_r_RVALID.read())))) {
        buf_addr_read_reg_225 = m_axi_buf_r_RDATA.read();
        key_addr_read_reg_220 = m_axi_key_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_135_p2.read()))) {
        buf_addr_reg_207 = sum1_fu_150_p2.read();
        sum_reg_202 = sum_fu_145_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_11_reg_194 = i_11_fu_125_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        key_addr_reg_214 = sum3_fu_164_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_buf_r_AWREADY.read(), ap_const_logic_1))) {
        tmp_34_reg_230 = tmp_34_fu_175_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_42_reg_189 = tmp_42_fu_121_p1.read();
    }
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void a0_aes_addRoundKey::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void a0_aes_addRoundKey::thread_ap_block_state11() {
    ap_block_state11 = (esl_seteq<1,1,1>(ap_const_logic_0, m_axi_key_RVALID.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_buf_r_RVALID.read()));
}

void a0_aes_addRoundKey::thread_ap_block_state4_io() {
    ap_block_state4_io = (esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_key_ARREADY.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_buf_r_ARREADY.read()));
}

void a0_aes_addRoundKey::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_fu_135_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_135_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_ap_sig_ioackin_m_axi_buf_r_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_ARREADY.read())) {
        ap_sig_ioackin_m_axi_buf_r_ARREADY = m_axi_buf_r_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_buf_r_ARREADY = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_ap_sig_ioackin_m_axi_buf_r_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_AWREADY.read())) {
        ap_sig_ioackin_m_axi_buf_r_AWREADY = m_axi_buf_r_AWREADY.read();
    } else {
        ap_sig_ioackin_m_axi_buf_r_AWREADY = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_ap_sig_ioackin_m_axi_buf_r_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_WREADY.read())) {
        ap_sig_ioackin_m_axi_buf_r_WREADY = m_axi_buf_r_WREADY.read();
    } else {
        ap_sig_ioackin_m_axi_buf_r_WREADY = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_ap_sig_ioackin_m_axi_key_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_key_ARREADY.read())) {
        ap_sig_ioackin_m_axi_key_ARREADY = m_axi_key_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_key_ARREADY = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_buf_r_blk_n_AR() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_r_blk_n_AR = m_axi_buf_r_ARREADY.read();
    } else {
        buf_r_blk_n_AR = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_buf_r_blk_n_AW() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buf_r_blk_n_AW = m_axi_buf_r_AWREADY.read();
    } else {
        buf_r_blk_n_AW = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_buf_r_blk_n_B() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        buf_r_blk_n_B = m_axi_buf_r_BVALID.read();
    } else {
        buf_r_blk_n_B = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_buf_r_blk_n_R() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        buf_r_blk_n_R = m_axi_buf_r_RVALID.read();
    } else {
        buf_r_blk_n_R = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_buf_r_blk_n_W() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        buf_r_blk_n_W = m_axi_buf_r_WREADY.read();
    } else {
        buf_r_blk_n_W = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_i_11_cast_fu_131_p1() {
    i_11_cast_fu_131_p1 = esl_sext<8,5>(i_11_fu_125_p2.read());
}

void a0_aes_addRoundKey::thread_i_11_fu_125_p2() {
    i_11_fu_125_p2 = (!i_reg_110.read().is_01() || !ap_const_lv5_1F.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_110.read()) + sc_bigint<5>(ap_const_lv5_1F));
}

void a0_aes_addRoundKey::thread_key_blk_n_AR() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        key_blk_n_AR = m_axi_key_ARREADY.read();
    } else {
        key_blk_n_AR = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_key_blk_n_R() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        key_blk_n_R = m_axi_key_RVALID.read();
    } else {
        key_blk_n_R = ap_const_logic_1;
    }
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARADDR() {
    m_axi_buf_r_ARADDR = buf_addr_reg_207.read();
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARBURST() {
    m_axi_buf_r_ARBURST = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARCACHE() {
    m_axi_buf_r_ARCACHE = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARID() {
    m_axi_buf_r_ARID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARLEN() {
    m_axi_buf_r_ARLEN = ap_const_lv32_1;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARLOCK() {
    m_axi_buf_r_ARLOCK = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARPROT() {
    m_axi_buf_r_ARPROT = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARQOS() {
    m_axi_buf_r_ARQOS = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARREGION() {
    m_axi_buf_r_ARREGION = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARSIZE() {
    m_axi_buf_r_ARSIZE = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARUSER() {
    m_axi_buf_r_ARUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_ARREADY.read()))) {
        m_axi_buf_r_ARVALID = ap_const_logic_1;
    } else {
        m_axi_buf_r_ARVALID = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWADDR() {
    m_axi_buf_r_AWADDR = buf_addr_reg_207.read();
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWBURST() {
    m_axi_buf_r_AWBURST = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWCACHE() {
    m_axi_buf_r_AWCACHE = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWID() {
    m_axi_buf_r_AWID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWLEN() {
    m_axi_buf_r_AWLEN = ap_const_lv32_1;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWLOCK() {
    m_axi_buf_r_AWLOCK = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWPROT() {
    m_axi_buf_r_AWPROT = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWQOS() {
    m_axi_buf_r_AWQOS = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWREGION() {
    m_axi_buf_r_AWREGION = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWSIZE() {
    m_axi_buf_r_AWSIZE = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWUSER() {
    m_axi_buf_r_AWUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_AWREADY.read()))) {
        m_axi_buf_r_AWVALID = ap_const_logic_1;
    } else {
        m_axi_buf_r_AWVALID = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
         esl_seteq<1,1,1>(m_axi_buf_r_BVALID.read(), ap_const_logic_1))) {
        m_axi_buf_r_BREADY = ap_const_logic_1;
    } else {
        m_axi_buf_r_BREADY = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, m_axi_key_RVALID.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_buf_r_RVALID.read())))) {
        m_axi_buf_r_RREADY = ap_const_logic_1;
    } else {
        m_axi_buf_r_RREADY = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WDATA() {
    m_axi_buf_r_WDATA = tmp_34_reg_230.read();
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WID() {
    m_axi_buf_r_WID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WLAST() {
    m_axi_buf_r_WLAST = ap_const_logic_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WSTRB() {
    m_axi_buf_r_WSTRB = ap_const_lv1_1;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WUSER() {
    m_axi_buf_r_WUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_buf_r_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_buf_r_WREADY.read()))) {
        m_axi_buf_r_WVALID = ap_const_logic_1;
    } else {
        m_axi_buf_r_WVALID = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_key_ARADDR() {
    m_axi_key_ARADDR = key_addr_reg_214.read();
}

void a0_aes_addRoundKey::thread_m_axi_key_ARBURST() {
    m_axi_key_ARBURST = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARCACHE() {
    m_axi_key_ARCACHE = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARID() {
    m_axi_key_ARID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARLEN() {
    m_axi_key_ARLEN = ap_const_lv32_1;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARLOCK() {
    m_axi_key_ARLOCK = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARPROT() {
    m_axi_key_ARPROT = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARQOS() {
    m_axi_key_ARQOS = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARREGION() {
    m_axi_key_ARREGION = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARSIZE() {
    m_axi_key_ARSIZE = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARUSER() {
    m_axi_key_ARUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_key_ARREADY.read()))) {
        m_axi_key_ARVALID = ap_const_logic_1;
    } else {
        m_axi_key_ARVALID = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_key_AWADDR() {
    m_axi_key_AWADDR = ap_const_lv32_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWBURST() {
    m_axi_key_AWBURST = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWCACHE() {
    m_axi_key_AWCACHE = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWID() {
    m_axi_key_AWID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWLEN() {
    m_axi_key_AWLEN = ap_const_lv32_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWLOCK() {
    m_axi_key_AWLOCK = ap_const_lv2_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWPROT() {
    m_axi_key_AWPROT = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWQOS() {
    m_axi_key_AWQOS = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWREGION() {
    m_axi_key_AWREGION = ap_const_lv4_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWSIZE() {
    m_axi_key_AWSIZE = ap_const_lv3_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWUSER() {
    m_axi_key_AWUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_AWVALID() {
    m_axi_key_AWVALID = ap_const_logic_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_BREADY() {
    m_axi_key_BREADY = ap_const_logic_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, m_axi_key_RVALID.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_buf_r_RVALID.read())))) {
        m_axi_key_RREADY = ap_const_logic_1;
    } else {
        m_axi_key_RREADY = ap_const_logic_0;
    }
}

void a0_aes_addRoundKey::thread_m_axi_key_WDATA() {
    m_axi_key_WDATA = ap_const_lv8_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_WID() {
    m_axi_key_WID = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_WLAST() {
    m_axi_key_WLAST = ap_const_logic_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_WSTRB() {
    m_axi_key_WSTRB = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_WUSER() {
    m_axi_key_WUSER = ap_const_lv1_0;
}

void a0_aes_addRoundKey::thread_m_axi_key_WVALID() {
    m_axi_key_WVALID = ap_const_logic_0;
}

void a0_aes_addRoundKey::thread_sum1_fu_150_p2() {
    sum1_fu_150_p2 = (!tmp_s_fu_141_p1.read().is_01() || !buf_offset.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_s_fu_141_p1.read()) + sc_biguint<32>(buf_offset.read()));
}

void a0_aes_addRoundKey::thread_sum3_fu_164_p2() {
    sum3_fu_164_p2 = (!sum_cast_fu_161_p1.read().is_01() || !key_offset.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sum_cast_fu_161_p1.read()) + sc_biguint<32>(key_offset.read()));
}

void a0_aes_addRoundKey::thread_sum_cast_fu_161_p1() {
    sum_cast_fu_161_p1 = esl_zext<32,5>(sum_reg_202.read());
}

void a0_aes_addRoundKey::thread_sum_fu_145_p2() {
    sum_fu_145_p2 = (!i_11_fu_125_p2.read().is_01() || !tmp_42_reg_189.read().is_01())? sc_lv<5>(): (sc_biguint<5>(i_11_fu_125_p2.read()) + sc_biguint<5>(tmp_42_reg_189.read()));
}

void a0_aes_addRoundKey::thread_tmp_34_fu_175_p2() {
    tmp_34_fu_175_p2 = (buf_addr_read_reg_225.read() ^ key_addr_read_reg_220.read());
}

void a0_aes_addRoundKey::thread_tmp_42_fu_121_p1() {
    tmp_42_fu_121_p1 = key_offset_offset.read().range(5-1, 0);
}

void a0_aes_addRoundKey::thread_tmp_fu_135_p2() {
    tmp_fu_135_p2 = (!i_reg_110.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_110.read() == ap_const_lv5_0);
}

void a0_aes_addRoundKey::thread_tmp_s_fu_141_p1() {
    tmp_s_fu_141_p1 = esl_zext<32,8>(i_11_cast_fu_131_p1.read());
}

void a0_aes_addRoundKey::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_135_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_block_state4_io.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, m_axi_key_RVALID.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_buf_r_RVALID.read())))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_buf_r_AWREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_buf_r_WREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(m_axi_buf_r_BVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state18;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

