# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1.xci
# IP: The module: 'pynq_s00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1.xci
# IP: The module: 'pynq_s00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/local/tmp.tEdaivbEa4/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_s00_regslice_1/pynq_s00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynq_s00_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
