#!/bin/bash -e

if [ $# -ne 2 ]
then
  echo "Usage: $0 <Directory with makefiles of SDSoC project> <Serial device>"
  exit 1
fi

source ${SDSOC_ROOT}/settings64.sh

cd "$1"

ELF_FILE=$(grep "^main-build:" makefile | awk '{ print $2 }')
BIT_FILE="${ELF_FILE}.bit"

cat > ${I3_ROOT}/Code/Scripts/Run.tcl << END
connect
fpga ${BIT_FILE}
targets 2
rst
source $1/_sds/p0/ipi/zed.sdk/ps7_init.tcl
ps7_init
ps7_post_config
dow ${ELF_FILE}
con
END

Close_serial_line()
{
  pkill -P $$ || true
}

trap Close_serial_line EXIT

cat $2 | stdbuf tee ${I3_ROOT}/Code/Scripts/Output.txt | grep -lq "TEST PASSED" &
sdx -batch -source ${I3_ROOT}/Code/Scripts/Run.tcl
echo "Waiting for output..."
wait || true
echo "Done"

