// Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2017.1_sdx (lin64) Build 1915620 Thu Jun 22 17:54:59 MDT 2017
// Date        : Wed Oct 31 14:55:45 2018
// Host        : icgrid46 running 64-bit openSUSE Leap 42.3
// Command     : write_verilog -force -mode synth_stub
//               /scratch/local/tmp.MCX0lb37KH/_sds/p0/ipi/pynq.srcs/sources_1/bd/pynq/ip/pynq_encrypt_1_if_0/pynq_encrypt_1_if_0_stub.v
// Design      : pynq_encrypt_1_if_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7z020clg400-1
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* X_CORE_INFO = "top,Vivado 2017.1_sdx" *)
module pynq_encrypt_1_if_0(s_axi_aclk, s_axi_aresetn, S_AXI_AWADDR, 
  S_AXI_AWPROT, S_AXI_AWVALID, S_AXI_AWREADY, S_AXI_WDATA, S_AXI_WSTRB, S_AXI_WVALID, 
  S_AXI_WREADY, S_AXI_BRESP, S_AXI_BVALID, S_AXI_BREADY, S_AXI_ARADDR, S_AXI_ARPROT, 
  S_AXI_ARVALID, S_AXI_ARREADY, S_AXI_RDATA, S_AXI_RRESP, S_AXI_RVALID, S_AXI_RREADY, acc_aclk, 
  acc_aresetn, ap_resetn, ap_clk, ap_start, ap_idle, ap_done, ap_ready, ap_continue, 
  ap_iscalar_0_dout, ap_iscalar_1_dout, ap_iscalar_2_dout, ap_iscalar_3_dout, 
  s_axis_bram_0_aclk, s_axis_bram_0_aresetn, s_axis_bram_0_tlast, s_axis_bram_0_tvalid, 
  s_axis_bram_0_tkeep, s_axis_bram_0_tstrb, s_axis_bram_0_tdata, s_axis_bram_0_tready, 
  ap_bram_iarg_0_addr0, ap_bram_iarg_0_din0, ap_bram_iarg_0_dout0, ap_bram_iarg_0_clk0, 
  ap_bram_iarg_0_rst0, ap_bram_iarg_0_we0, ap_bram_iarg_0_en0, AP_AXIMM_0_AWADDR, 
  AP_AXIMM_0_AWLEN, AP_AXIMM_0_AWSIZE, AP_AXIMM_0_AWBURST, AP_AXIMM_0_AWLOCK, 
  AP_AXIMM_0_AWCACHE, AP_AXIMM_0_AWPROT, AP_AXIMM_0_AWREGION, AP_AXIMM_0_AWQOS, 
  AP_AXIMM_0_AWVALID, AP_AXIMM_0_AWREADY, AP_AXIMM_0_WDATA, AP_AXIMM_0_WSTRB, 
  AP_AXIMM_0_WLAST, AP_AXIMM_0_WVALID, AP_AXIMM_0_WREADY, AP_AXIMM_0_BRESP, 
  AP_AXIMM_0_BVALID, AP_AXIMM_0_BREADY, AP_AXIMM_0_ARADDR, AP_AXIMM_0_ARLEN, 
  AP_AXIMM_0_ARSIZE, AP_AXIMM_0_ARBURST, AP_AXIMM_0_ARLOCK, AP_AXIMM_0_ARCACHE, 
  AP_AXIMM_0_ARPROT, AP_AXIMM_0_ARREGION, AP_AXIMM_0_ARQOS, AP_AXIMM_0_ARVALID, 
  AP_AXIMM_0_ARREADY, AP_AXIMM_0_RDATA, AP_AXIMM_0_RRESP, AP_AXIMM_0_RLAST, 
  AP_AXIMM_0_RVALID, AP_AXIMM_0_RREADY, M_AXIMM_0_AWADDR, M_AXIMM_0_AWLEN, 
  M_AXIMM_0_AWSIZE, M_AXIMM_0_AWBURST, M_AXIMM_0_AWLOCK, M_AXIMM_0_AWCACHE, 
  M_AXIMM_0_AWPROT, M_AXIMM_0_AWREGION, M_AXIMM_0_AWQOS, M_AXIMM_0_AWVALID, 
  M_AXIMM_0_AWREADY, M_AXIMM_0_WDATA, M_AXIMM_0_WSTRB, M_AXIMM_0_WLAST, M_AXIMM_0_WVALID, 
  M_AXIMM_0_WREADY, M_AXIMM_0_BRESP, M_AXIMM_0_BVALID, M_AXIMM_0_BREADY, M_AXIMM_0_ARADDR, 
  M_AXIMM_0_ARLEN, M_AXIMM_0_ARSIZE, M_AXIMM_0_ARBURST, M_AXIMM_0_ARLOCK, 
  M_AXIMM_0_ARCACHE, M_AXIMM_0_ARPROT, M_AXIMM_0_ARREGION, M_AXIMM_0_ARQOS, 
  M_AXIMM_0_ARVALID, M_AXIMM_0_ARREADY, M_AXIMM_0_RDATA, M_AXIMM_0_RRESP, M_AXIMM_0_RLAST, 
  M_AXIMM_0_RVALID, M_AXIMM_0_RREADY, AP_AXIMM_1_AWADDR, AP_AXIMM_1_AWLEN, 
  AP_AXIMM_1_AWSIZE, AP_AXIMM_1_AWBURST, AP_AXIMM_1_AWLOCK, AP_AXIMM_1_AWCACHE, 
  AP_AXIMM_1_AWPROT, AP_AXIMM_1_AWREGION, AP_AXIMM_1_AWQOS, AP_AXIMM_1_AWVALID, 
  AP_AXIMM_1_AWREADY, AP_AXIMM_1_WDATA, AP_AXIMM_1_WSTRB, AP_AXIMM_1_WLAST, 
  AP_AXIMM_1_WVALID, AP_AXIMM_1_WREADY, AP_AXIMM_1_BRESP, AP_AXIMM_1_BVALID, 
  AP_AXIMM_1_BREADY, AP_AXIMM_1_ARADDR, AP_AXIMM_1_ARLEN, AP_AXIMM_1_ARSIZE, 
  AP_AXIMM_1_ARBURST, AP_AXIMM_1_ARLOCK, AP_AXIMM_1_ARCACHE, AP_AXIMM_1_ARPROT, 
  AP_AXIMM_1_ARREGION, AP_AXIMM_1_ARQOS, AP_AXIMM_1_ARVALID, AP_AXIMM_1_ARREADY, 
  AP_AXIMM_1_RDATA, AP_AXIMM_1_RRESP, AP_AXIMM_1_RLAST, AP_AXIMM_1_RVALID, 
  AP_AXIMM_1_RREADY, M_AXIMM_1_AWADDR, M_AXIMM_1_AWLEN, M_AXIMM_1_AWSIZE, 
  M_AXIMM_1_AWBURST, M_AXIMM_1_AWLOCK, M_AXIMM_1_AWCACHE, M_AXIMM_1_AWPROT, 
  M_AXIMM_1_AWREGION, M_AXIMM_1_AWQOS, M_AXIMM_1_AWVALID, M_AXIMM_1_AWREADY, 
  M_AXIMM_1_WDATA, M_AXIMM_1_WSTRB, M_AXIMM_1_WLAST, M_AXIMM_1_WVALID, M_AXIMM_1_WREADY, 
  M_AXIMM_1_BRESP, M_AXIMM_1_BVALID, M_AXIMM_1_BREADY, M_AXIMM_1_ARADDR, M_AXIMM_1_ARLEN, 
  M_AXIMM_1_ARSIZE, M_AXIMM_1_ARBURST, M_AXIMM_1_ARLOCK, M_AXIMM_1_ARCACHE, 
  M_AXIMM_1_ARPROT, M_AXIMM_1_ARREGION, M_AXIMM_1_ARQOS, M_AXIMM_1_ARVALID, 
  M_AXIMM_1_ARREADY, M_AXIMM_1_RDATA, M_AXIMM_1_RRESP, M_AXIMM_1_RLAST, M_AXIMM_1_RVALID, 
  M_AXIMM_1_RREADY, AP_AXIMM_2_AWADDR, AP_AXIMM_2_AWLEN, AP_AXIMM_2_AWSIZE, 
  AP_AXIMM_2_AWBURST, AP_AXIMM_2_AWLOCK, AP_AXIMM_2_AWCACHE, AP_AXIMM_2_AWPROT, 
  AP_AXIMM_2_AWREGION, AP_AXIMM_2_AWQOS, AP_AXIMM_2_AWVALID, AP_AXIMM_2_AWREADY, 
  AP_AXIMM_2_WDATA, AP_AXIMM_2_WSTRB, AP_AXIMM_2_WLAST, AP_AXIMM_2_WVALID, 
  AP_AXIMM_2_WREADY, AP_AXIMM_2_BRESP, AP_AXIMM_2_BVALID, AP_AXIMM_2_BREADY, 
  AP_AXIMM_2_ARADDR, AP_AXIMM_2_ARLEN, AP_AXIMM_2_ARSIZE, AP_AXIMM_2_ARBURST, 
  AP_AXIMM_2_ARLOCK, AP_AXIMM_2_ARCACHE, AP_AXIMM_2_ARPROT, AP_AXIMM_2_ARREGION, 
  AP_AXIMM_2_ARQOS, AP_AXIMM_2_ARVALID, AP_AXIMM_2_ARREADY, AP_AXIMM_2_RDATA, 
  AP_AXIMM_2_RRESP, AP_AXIMM_2_RLAST, AP_AXIMM_2_RVALID, AP_AXIMM_2_RREADY, 
  M_AXIMM_2_AWADDR, M_AXIMM_2_AWLEN, M_AXIMM_2_AWSIZE, M_AXIMM_2_AWBURST, M_AXIMM_2_AWLOCK, 
  M_AXIMM_2_AWCACHE, M_AXIMM_2_AWPROT, M_AXIMM_2_AWREGION, M_AXIMM_2_AWQOS, 
  M_AXIMM_2_AWVALID, M_AXIMM_2_AWREADY, M_AXIMM_2_WDATA, M_AXIMM_2_WSTRB, M_AXIMM_2_WLAST, 
  M_AXIMM_2_WVALID, M_AXIMM_2_WREADY, M_AXIMM_2_BRESP, M_AXIMM_2_BVALID, M_AXIMM_2_BREADY, 
  M_AXIMM_2_ARADDR, M_AXIMM_2_ARLEN, M_AXIMM_2_ARSIZE, M_AXIMM_2_ARBURST, M_AXIMM_2_ARLOCK, 
  M_AXIMM_2_ARCACHE, M_AXIMM_2_ARPROT, M_AXIMM_2_ARREGION, M_AXIMM_2_ARQOS, 
  M_AXIMM_2_ARVALID, M_AXIMM_2_ARREADY, M_AXIMM_2_RDATA, M_AXIMM_2_RRESP, M_AXIMM_2_RLAST, 
  M_AXIMM_2_RVALID, M_AXIMM_2_RREADY, AP_AXIMM_3_AWADDR, AP_AXIMM_3_AWLEN, 
  AP_AXIMM_3_AWSIZE, AP_AXIMM_3_AWBURST, AP_AXIMM_3_AWLOCK, AP_AXIMM_3_AWCACHE, 
  AP_AXIMM_3_AWPROT, AP_AXIMM_3_AWREGION, AP_AXIMM_3_AWQOS, AP_AXIMM_3_AWVALID, 
  AP_AXIMM_3_AWREADY, AP_AXIMM_3_WDATA, AP_AXIMM_3_WSTRB, AP_AXIMM_3_WLAST, 
  AP_AXIMM_3_WVALID, AP_AXIMM_3_WREADY, AP_AXIMM_3_BRESP, AP_AXIMM_3_BVALID, 
  AP_AXIMM_3_BREADY, AP_AXIMM_3_ARADDR, AP_AXIMM_3_ARLEN, AP_AXIMM_3_ARSIZE, 
  AP_AXIMM_3_ARBURST, AP_AXIMM_3_ARLOCK, AP_AXIMM_3_ARCACHE, AP_AXIMM_3_ARPROT, 
  AP_AXIMM_3_ARREGION, AP_AXIMM_3_ARQOS, AP_AXIMM_3_ARVALID, AP_AXIMM_3_ARREADY, 
  AP_AXIMM_3_RDATA, AP_AXIMM_3_RRESP, AP_AXIMM_3_RLAST, AP_AXIMM_3_RVALID, 
  AP_AXIMM_3_RREADY, M_AXIMM_3_AWADDR, M_AXIMM_3_AWLEN, M_AXIMM_3_AWSIZE, 
  M_AXIMM_3_AWBURST, M_AXIMM_3_AWLOCK, M_AXIMM_3_AWCACHE, M_AXIMM_3_AWPROT, 
  M_AXIMM_3_AWREGION, M_AXIMM_3_AWQOS, M_AXIMM_3_AWVALID, M_AXIMM_3_AWREADY, 
  M_AXIMM_3_WDATA, M_AXIMM_3_WSTRB, M_AXIMM_3_WLAST, M_AXIMM_3_WVALID, M_AXIMM_3_WREADY, 
  M_AXIMM_3_BRESP, M_AXIMM_3_BVALID, M_AXIMM_3_BREADY, M_AXIMM_3_ARADDR, M_AXIMM_3_ARLEN, 
  M_AXIMM_3_ARSIZE, M_AXIMM_3_ARBURST, M_AXIMM_3_ARLOCK, M_AXIMM_3_ARCACHE, 
  M_AXIMM_3_ARPROT, M_AXIMM_3_ARREGION, M_AXIMM_3_ARQOS, M_AXIMM_3_ARVALID, 
  M_AXIMM_3_ARREADY, M_AXIMM_3_RDATA, M_AXIMM_3_RRESP, M_AXIMM_3_RLAST, M_AXIMM_3_RVALID, 
  M_AXIMM_3_RREADY)
/* synthesis syn_black_box black_box_pad_pin="s_axi_aclk,s_axi_aresetn,S_AXI_AWADDR[31:0],S_AXI_AWPROT[2:0],S_AXI_AWVALID,S_AXI_AWREADY,S_AXI_WDATA[31:0],S_AXI_WSTRB[3:0],S_AXI_WVALID,S_AXI_WREADY,S_AXI_BRESP[1:0],S_AXI_BVALID,S_AXI_BREADY,S_AXI_ARADDR[31:0],S_AXI_ARPROT[2:0],S_AXI_ARVALID,S_AXI_ARREADY,S_AXI_RDATA[31:0],S_AXI_RRESP[1:0],S_AXI_RVALID,S_AXI_RREADY,acc_aclk,acc_aresetn,ap_resetn,ap_clk,ap_start,ap_idle,ap_done,ap_ready,ap_continue,ap_iscalar_0_dout[31:0],ap_iscalar_1_dout[31:0],ap_iscalar_2_dout[31:0],ap_iscalar_3_dout[31:0],s_axis_bram_0_aclk,s_axis_bram_0_aresetn,s_axis_bram_0_tlast,s_axis_bram_0_tvalid,s_axis_bram_0_tkeep[7:0],s_axis_bram_0_tstrb[7:0],s_axis_bram_0_tdata[63:0],s_axis_bram_0_tready,ap_bram_iarg_0_addr0[4:0],ap_bram_iarg_0_din0[7:0],ap_bram_iarg_0_dout0[7:0],ap_bram_iarg_0_clk0,ap_bram_iarg_0_rst0,ap_bram_iarg_0_we0[0:0],ap_bram_iarg_0_en0,AP_AXIMM_0_AWADDR[31:0],AP_AXIMM_0_AWLEN[7:0],AP_AXIMM_0_AWSIZE[2:0],AP_AXIMM_0_AWBURST[1:0],AP_AXIMM_0_AWLOCK[1:0],AP_AXIMM_0_AWCACHE[3:0],AP_AXIMM_0_AWPROT[2:0],AP_AXIMM_0_AWREGION[3:0],AP_AXIMM_0_AWQOS[3:0],AP_AXIMM_0_AWVALID,AP_AXIMM_0_AWREADY,AP_AXIMM_0_WDATA[31:0],AP_AXIMM_0_WSTRB[3:0],AP_AXIMM_0_WLAST,AP_AXIMM_0_WVALID,AP_AXIMM_0_WREADY,AP_AXIMM_0_BRESP[1:0],AP_AXIMM_0_BVALID,AP_AXIMM_0_BREADY,AP_AXIMM_0_ARADDR[31:0],AP_AXIMM_0_ARLEN[7:0],AP_AXIMM_0_ARSIZE[2:0],AP_AXIMM_0_ARBURST[1:0],AP_AXIMM_0_ARLOCK[1:0],AP_AXIMM_0_ARCACHE[3:0],AP_AXIMM_0_ARPROT[2:0],AP_AXIMM_0_ARREGION[3:0],AP_AXIMM_0_ARQOS[3:0],AP_AXIMM_0_ARVALID,AP_AXIMM_0_ARREADY,AP_AXIMM_0_RDATA[31:0],AP_AXIMM_0_RRESP[1:0],AP_AXIMM_0_RLAST,AP_AXIMM_0_RVALID,AP_AXIMM_0_RREADY,M_AXIMM_0_AWADDR[31:0],M_AXIMM_0_AWLEN[7:0],M_AXIMM_0_AWSIZE[2:0],M_AXIMM_0_AWBURST[1:0],M_AXIMM_0_AWLOCK[1:0],M_AXIMM_0_AWCACHE[3:0],M_AXIMM_0_AWPROT[2:0],M_AXIMM_0_AWREGION[3:0],M_AXIMM_0_AWQOS[3:0],M_AXIMM_0_AWVALID,M_AXIMM_0_AWREADY,M_AXIMM_0_WDATA[31:0],M_AXIMM_0_WSTRB[3:0],M_AXIMM_0_WLAST,M_AXIMM_0_WVALID,M_AXIMM_0_WREADY,M_AXIMM_0_BRESP[1:0],M_AXIMM_0_BVALID,M_AXIMM_0_BREADY,M_AXIMM_0_ARADDR[31:0],M_AXIMM_0_ARLEN[7:0],M_AXIMM_0_ARSIZE[2:0],M_AXIMM_0_ARBURST[1:0],M_AXIMM_0_ARLOCK[1:0],M_AXIMM_0_ARCACHE[3:0],M_AXIMM_0_ARPROT[2:0],M_AXIMM_0_ARREGION[3:0],M_AXIMM_0_ARQOS[3:0],M_AXIMM_0_ARVALID,M_AXIMM_0_ARREADY,M_AXIMM_0_RDATA[31:0],M_AXIMM_0_RRESP[1:0],M_AXIMM_0_RLAST,M_AXIMM_0_RVALID,M_AXIMM_0_RREADY,AP_AXIMM_1_AWADDR[31:0],AP_AXIMM_1_AWLEN[7:0],AP_AXIMM_1_AWSIZE[2:0],AP_AXIMM_1_AWBURST[1:0],AP_AXIMM_1_AWLOCK[1:0],AP_AXIMM_1_AWCACHE[3:0],AP_AXIMM_1_AWPROT[2:0],AP_AXIMM_1_AWREGION[3:0],AP_AXIMM_1_AWQOS[3:0],AP_AXIMM_1_AWVALID,AP_AXIMM_1_AWREADY,AP_AXIMM_1_WDATA[31:0],AP_AXIMM_1_WSTRB[3:0],AP_AXIMM_1_WLAST,AP_AXIMM_1_WVALID,AP_AXIMM_1_WREADY,AP_AXIMM_1_BRESP[1:0],AP_AXIMM_1_BVALID,AP_AXIMM_1_BREADY,AP_AXIMM_1_ARADDR[31:0],AP_AXIMM_1_ARLEN[7:0],AP_AXIMM_1_ARSIZE[2:0],AP_AXIMM_1_ARBURST[1:0],AP_AXIMM_1_ARLOCK[1:0],AP_AXIMM_1_ARCACHE[3:0],AP_AXIMM_1_ARPROT[2:0],AP_AXIMM_1_ARREGION[3:0],AP_AXIMM_1_ARQOS[3:0],AP_AXIMM_1_ARVALID,AP_AXIMM_1_ARREADY,AP_AXIMM_1_RDATA[31:0],AP_AXIMM_1_RRESP[1:0],AP_AXIMM_1_RLAST,AP_AXIMM_1_RVALID,AP_AXIMM_1_RREADY,M_AXIMM_1_AWADDR[31:0],M_AXIMM_1_AWLEN[7:0],M_AXIMM_1_AWSIZE[2:0],M_AXIMM_1_AWBURST[1:0],M_AXIMM_1_AWLOCK[1:0],M_AXIMM_1_AWCACHE[3:0],M_AXIMM_1_AWPROT[2:0],M_AXIMM_1_AWREGION[3:0],M_AXIMM_1_AWQOS[3:0],M_AXIMM_1_AWVALID,M_AXIMM_1_AWREADY,M_AXIMM_1_WDATA[31:0],M_AXIMM_1_WSTRB[3:0],M_AXIMM_1_WLAST,M_AXIMM_1_WVALID,M_AXIMM_1_WREADY,M_AXIMM_1_BRESP[1:0],M_AXIMM_1_BVALID,M_AXIMM_1_BREADY,M_AXIMM_1_ARADDR[31:0],M_AXIMM_1_ARLEN[7:0],M_AXIMM_1_ARSIZE[2:0],M_AXIMM_1_ARBURST[1:0],M_AXIMM_1_ARLOCK[1:0],M_AXIMM_1_ARCACHE[3:0],M_AXIMM_1_ARPROT[2:0],M_AXIMM_1_ARREGION[3:0],M_AXIMM_1_ARQOS[3:0],M_AXIMM_1_ARVALID,M_AXIMM_1_ARREADY,M_AXIMM_1_RDATA[31:0],M_AXIMM_1_RRESP[1:0],M_AXIMM_1_RLAST,M_AXIMM_1_RVALID,M_AXIMM_1_RREADY,AP_AXIMM_2_AWADDR[31:0],AP_AXIMM_2_AWLEN[7:0],AP_AXIMM_2_AWSIZE[2:0],AP_AXIMM_2_AWBURST[1:0],AP_AXIMM_2_AWLOCK[1:0],AP_AXIMM_2_AWCACHE[3:0],AP_AXIMM_2_AWPROT[2:0],AP_AXIMM_2_AWREGION[3:0],AP_AXIMM_2_AWQOS[3:0],AP_AXIMM_2_AWVALID,AP_AXIMM_2_AWREADY,AP_AXIMM_2_WDATA[31:0],AP_AXIMM_2_WSTRB[3:0],AP_AXIMM_2_WLAST,AP_AXIMM_2_WVALID,AP_AXIMM_2_WREADY,AP_AXIMM_2_BRESP[1:0],AP_AXIMM_2_BVALID,AP_AXIMM_2_BREADY,AP_AXIMM_2_ARADDR[31:0],AP_AXIMM_2_ARLEN[7:0],AP_AXIMM_2_ARSIZE[2:0],AP_AXIMM_2_ARBURST[1:0],AP_AXIMM_2_ARLOCK[1:0],AP_AXIMM_2_ARCACHE[3:0],AP_AXIMM_2_ARPROT[2:0],AP_AXIMM_2_ARREGION[3:0],AP_AXIMM_2_ARQOS[3:0],AP_AXIMM_2_ARVALID,AP_AXIMM_2_ARREADY,AP_AXIMM_2_RDATA[31:0],AP_AXIMM_2_RRESP[1:0],AP_AXIMM_2_RLAST,AP_AXIMM_2_RVALID,AP_AXIMM_2_RREADY,M_AXIMM_2_AWADDR[31:0],M_AXIMM_2_AWLEN[7:0],M_AXIMM_2_AWSIZE[2:0],M_AXIMM_2_AWBURST[1:0],M_AXIMM_2_AWLOCK[1:0],M_AXIMM_2_AWCACHE[3:0],M_AXIMM_2_AWPROT[2:0],M_AXIMM_2_AWREGION[3:0],M_AXIMM_2_AWQOS[3:0],M_AXIMM_2_AWVALID,M_AXIMM_2_AWREADY,M_AXIMM_2_WDATA[31:0],M_AXIMM_2_WSTRB[3:0],M_AXIMM_2_WLAST,M_AXIMM_2_WVALID,M_AXIMM_2_WREADY,M_AXIMM_2_BRESP[1:0],M_AXIMM_2_BVALID,M_AXIMM_2_BREADY,M_AXIMM_2_ARADDR[31:0],M_AXIMM_2_ARLEN[7:0],M_AXIMM_2_ARSIZE[2:0],M_AXIMM_2_ARBURST[1:0],M_AXIMM_2_ARLOCK[1:0],M_AXIMM_2_ARCACHE[3:0],M_AXIMM_2_ARPROT[2:0],M_AXIMM_2_ARREGION[3:0],M_AXIMM_2_ARQOS[3:0],M_AXIMM_2_ARVALID,M_AXIMM_2_ARREADY,M_AXIMM_2_RDATA[31:0],M_AXIMM_2_RRESP[1:0],M_AXIMM_2_RLAST,M_AXIMM_2_RVALID,M_AXIMM_2_RREADY,AP_AXIMM_3_AWADDR[31:0],AP_AXIMM_3_AWLEN[7:0],AP_AXIMM_3_AWSIZE[2:0],AP_AXIMM_3_AWBURST[1:0],AP_AXIMM_3_AWLOCK[1:0],AP_AXIMM_3_AWCACHE[3:0],AP_AXIMM_3_AWPROT[2:0],AP_AXIMM_3_AWREGION[3:0],AP_AXIMM_3_AWQOS[3:0],AP_AXIMM_3_AWVALID,AP_AXIMM_3_AWREADY,AP_AXIMM_3_WDATA[31:0],AP_AXIMM_3_WSTRB[3:0],AP_AXIMM_3_WLAST,AP_AXIMM_3_WVALID,AP_AXIMM_3_WREADY,AP_AXIMM_3_BRESP[1:0],AP_AXIMM_3_BVALID,AP_AXIMM_3_BREADY,AP_AXIMM_3_ARADDR[31:0],AP_AXIMM_3_ARLEN[7:0],AP_AXIMM_3_ARSIZE[2:0],AP_AXIMM_3_ARBURST[1:0],AP_AXIMM_3_ARLOCK[1:0],AP_AXIMM_3_ARCACHE[3:0],AP_AXIMM_3_ARPROT[2:0],AP_AXIMM_3_ARREGION[3:0],AP_AXIMM_3_ARQOS[3:0],AP_AXIMM_3_ARVALID,AP_AXIMM_3_ARREADY,AP_AXIMM_3_RDATA[31:0],AP_AXIMM_3_RRESP[1:0],AP_AXIMM_3_RLAST,AP_AXIMM_3_RVALID,AP_AXIMM_3_RREADY,M_AXIMM_3_AWADDR[31:0],M_AXIMM_3_AWLEN[7:0],M_AXIMM_3_AWSIZE[2:0],M_AXIMM_3_AWBURST[1:0],M_AXIMM_3_AWLOCK[1:0],M_AXIMM_3_AWCACHE[3:0],M_AXIMM_3_AWPROT[2:0],M_AXIMM_3_AWREGION[3:0],M_AXIMM_3_AWQOS[3:0],M_AXIMM_3_AWVALID,M_AXIMM_3_AWREADY,M_AXIMM_3_WDATA[31:0],M_AXIMM_3_WSTRB[3:0],M_AXIMM_3_WLAST,M_AXIMM_3_WVALID,M_AXIMM_3_WREADY,M_AXIMM_3_BRESP[1:0],M_AXIMM_3_BVALID,M_AXIMM_3_BREADY,M_AXIMM_3_ARADDR[31:0],M_AXIMM_3_ARLEN[7:0],M_AXIMM_3_ARSIZE[2:0],M_AXIMM_3_ARBURST[1:0],M_AXIMM_3_ARLOCK[1:0],M_AXIMM_3_ARCACHE[3:0],M_AXIMM_3_ARPROT[2:0],M_AXIMM_3_ARREGION[3:0],M_AXIMM_3_ARQOS[3:0],M_AXIMM_3_ARVALID,M_AXIMM_3_ARREADY,M_AXIMM_3_RDATA[31:0],M_AXIMM_3_RRESP[1:0],M_AXIMM_3_RLAST,M_AXIMM_3_RVALID,M_AXIMM_3_RREADY" */;
  input s_axi_aclk;
  input s_axi_aresetn;
  input [31:0]S_AXI_AWADDR;
  input [2:0]S_AXI_AWPROT;
  input S_AXI_AWVALID;
  output S_AXI_AWREADY;
  input [31:0]S_AXI_WDATA;
  input [3:0]S_AXI_WSTRB;
  input S_AXI_WVALID;
  output S_AXI_WREADY;
  output [1:0]S_AXI_BRESP;
  output S_AXI_BVALID;
  input S_AXI_BREADY;
  input [31:0]S_AXI_ARADDR;
  input [2:0]S_AXI_ARPROT;
  input S_AXI_ARVALID;
  output S_AXI_ARREADY;
  output [31:0]S_AXI_RDATA;
  output [1:0]S_AXI_RRESP;
  output S_AXI_RVALID;
  input S_AXI_RREADY;
  input acc_aclk;
  input acc_aresetn;
  output ap_resetn;
  output ap_clk;
  output ap_start;
  input ap_idle;
  input ap_done;
  input ap_ready;
  output ap_continue;
  output [31:0]ap_iscalar_0_dout;
  output [31:0]ap_iscalar_1_dout;
  output [31:0]ap_iscalar_2_dout;
  output [31:0]ap_iscalar_3_dout;
  input s_axis_bram_0_aclk;
  input s_axis_bram_0_aresetn;
  input s_axis_bram_0_tlast;
  input s_axis_bram_0_tvalid;
  input [7:0]s_axis_bram_0_tkeep;
  input [7:0]s_axis_bram_0_tstrb;
  input [63:0]s_axis_bram_0_tdata;
  output s_axis_bram_0_tready;
  input [4:0]ap_bram_iarg_0_addr0;
  input [7:0]ap_bram_iarg_0_din0;
  output [7:0]ap_bram_iarg_0_dout0;
  input ap_bram_iarg_0_clk0;
  input ap_bram_iarg_0_rst0;
  input [0:0]ap_bram_iarg_0_we0;
  input ap_bram_iarg_0_en0;
  input [31:0]AP_AXIMM_0_AWADDR;
  input [7:0]AP_AXIMM_0_AWLEN;
  input [2:0]AP_AXIMM_0_AWSIZE;
  input [1:0]AP_AXIMM_0_AWBURST;
  input [1:0]AP_AXIMM_0_AWLOCK;
  input [3:0]AP_AXIMM_0_AWCACHE;
  input [2:0]AP_AXIMM_0_AWPROT;
  input [3:0]AP_AXIMM_0_AWREGION;
  input [3:0]AP_AXIMM_0_AWQOS;
  input AP_AXIMM_0_AWVALID;
  output AP_AXIMM_0_AWREADY;
  input [31:0]AP_AXIMM_0_WDATA;
  input [3:0]AP_AXIMM_0_WSTRB;
  input AP_AXIMM_0_WLAST;
  input AP_AXIMM_0_WVALID;
  output AP_AXIMM_0_WREADY;
  output [1:0]AP_AXIMM_0_BRESP;
  output AP_AXIMM_0_BVALID;
  input AP_AXIMM_0_BREADY;
  input [31:0]AP_AXIMM_0_ARADDR;
  input [7:0]AP_AXIMM_0_ARLEN;
  input [2:0]AP_AXIMM_0_ARSIZE;
  input [1:0]AP_AXIMM_0_ARBURST;
  input [1:0]AP_AXIMM_0_ARLOCK;
  input [3:0]AP_AXIMM_0_ARCACHE;
  input [2:0]AP_AXIMM_0_ARPROT;
  input [3:0]AP_AXIMM_0_ARREGION;
  input [3:0]AP_AXIMM_0_ARQOS;
  input AP_AXIMM_0_ARVALID;
  output AP_AXIMM_0_ARREADY;
  output [31:0]AP_AXIMM_0_RDATA;
  output [1:0]AP_AXIMM_0_RRESP;
  output AP_AXIMM_0_RLAST;
  output AP_AXIMM_0_RVALID;
  input AP_AXIMM_0_RREADY;
  output [31:0]M_AXIMM_0_AWADDR;
  output [7:0]M_AXIMM_0_AWLEN;
  output [2:0]M_AXIMM_0_AWSIZE;
  output [1:0]M_AXIMM_0_AWBURST;
  output [1:0]M_AXIMM_0_AWLOCK;
  output [3:0]M_AXIMM_0_AWCACHE;
  output [2:0]M_AXIMM_0_AWPROT;
  output [3:0]M_AXIMM_0_AWREGION;
  output [3:0]M_AXIMM_0_AWQOS;
  output M_AXIMM_0_AWVALID;
  input M_AXIMM_0_AWREADY;
  output [31:0]M_AXIMM_0_WDATA;
  output [3:0]M_AXIMM_0_WSTRB;
  output M_AXIMM_0_WLAST;
  output M_AXIMM_0_WVALID;
  input M_AXIMM_0_WREADY;
  input [1:0]M_AXIMM_0_BRESP;
  input M_AXIMM_0_BVALID;
  output M_AXIMM_0_BREADY;
  output [31:0]M_AXIMM_0_ARADDR;
  output [7:0]M_AXIMM_0_ARLEN;
  output [2:0]M_AXIMM_0_ARSIZE;
  output [1:0]M_AXIMM_0_ARBURST;
  output [1:0]M_AXIMM_0_ARLOCK;
  output [3:0]M_AXIMM_0_ARCACHE;
  output [2:0]M_AXIMM_0_ARPROT;
  output [3:0]M_AXIMM_0_ARREGION;
  output [3:0]M_AXIMM_0_ARQOS;
  output M_AXIMM_0_ARVALID;
  input M_AXIMM_0_ARREADY;
  input [31:0]M_AXIMM_0_RDATA;
  input [1:0]M_AXIMM_0_RRESP;
  input M_AXIMM_0_RLAST;
  input M_AXIMM_0_RVALID;
  output M_AXIMM_0_RREADY;
  input [31:0]AP_AXIMM_1_AWADDR;
  input [7:0]AP_AXIMM_1_AWLEN;
  input [2:0]AP_AXIMM_1_AWSIZE;
  input [1:0]AP_AXIMM_1_AWBURST;
  input [1:0]AP_AXIMM_1_AWLOCK;
  input [3:0]AP_AXIMM_1_AWCACHE;
  input [2:0]AP_AXIMM_1_AWPROT;
  input [3:0]AP_AXIMM_1_AWREGION;
  input [3:0]AP_AXIMM_1_AWQOS;
  input AP_AXIMM_1_AWVALID;
  output AP_AXIMM_1_AWREADY;
  input [31:0]AP_AXIMM_1_WDATA;
  input [3:0]AP_AXIMM_1_WSTRB;
  input AP_AXIMM_1_WLAST;
  input AP_AXIMM_1_WVALID;
  output AP_AXIMM_1_WREADY;
  output [1:0]AP_AXIMM_1_BRESP;
  output AP_AXIMM_1_BVALID;
  input AP_AXIMM_1_BREADY;
  input [31:0]AP_AXIMM_1_ARADDR;
  input [7:0]AP_AXIMM_1_ARLEN;
  input [2:0]AP_AXIMM_1_ARSIZE;
  input [1:0]AP_AXIMM_1_ARBURST;
  input [1:0]AP_AXIMM_1_ARLOCK;
  input [3:0]AP_AXIMM_1_ARCACHE;
  input [2:0]AP_AXIMM_1_ARPROT;
  input [3:0]AP_AXIMM_1_ARREGION;
  input [3:0]AP_AXIMM_1_ARQOS;
  input AP_AXIMM_1_ARVALID;
  output AP_AXIMM_1_ARREADY;
  output [31:0]AP_AXIMM_1_RDATA;
  output [1:0]AP_AXIMM_1_RRESP;
  output AP_AXIMM_1_RLAST;
  output AP_AXIMM_1_RVALID;
  input AP_AXIMM_1_RREADY;
  output [31:0]M_AXIMM_1_AWADDR;
  output [7:0]M_AXIMM_1_AWLEN;
  output [2:0]M_AXIMM_1_AWSIZE;
  output [1:0]M_AXIMM_1_AWBURST;
  output [1:0]M_AXIMM_1_AWLOCK;
  output [3:0]M_AXIMM_1_AWCACHE;
  output [2:0]M_AXIMM_1_AWPROT;
  output [3:0]M_AXIMM_1_AWREGION;
  output [3:0]M_AXIMM_1_AWQOS;
  output M_AXIMM_1_AWVALID;
  input M_AXIMM_1_AWREADY;
  output [31:0]M_AXIMM_1_WDATA;
  output [3:0]M_AXIMM_1_WSTRB;
  output M_AXIMM_1_WLAST;
  output M_AXIMM_1_WVALID;
  input M_AXIMM_1_WREADY;
  input [1:0]M_AXIMM_1_BRESP;
  input M_AXIMM_1_BVALID;
  output M_AXIMM_1_BREADY;
  output [31:0]M_AXIMM_1_ARADDR;
  output [7:0]M_AXIMM_1_ARLEN;
  output [2:0]M_AXIMM_1_ARSIZE;
  output [1:0]M_AXIMM_1_ARBURST;
  output [1:0]M_AXIMM_1_ARLOCK;
  output [3:0]M_AXIMM_1_ARCACHE;
  output [2:0]M_AXIMM_1_ARPROT;
  output [3:0]M_AXIMM_1_ARREGION;
  output [3:0]M_AXIMM_1_ARQOS;
  output M_AXIMM_1_ARVALID;
  input M_AXIMM_1_ARREADY;
  input [31:0]M_AXIMM_1_RDATA;
  input [1:0]M_AXIMM_1_RRESP;
  input M_AXIMM_1_RLAST;
  input M_AXIMM_1_RVALID;
  output M_AXIMM_1_RREADY;
  input [31:0]AP_AXIMM_2_AWADDR;
  input [7:0]AP_AXIMM_2_AWLEN;
  input [2:0]AP_AXIMM_2_AWSIZE;
  input [1:0]AP_AXIMM_2_AWBURST;
  input [1:0]AP_AXIMM_2_AWLOCK;
  input [3:0]AP_AXIMM_2_AWCACHE;
  input [2:0]AP_AXIMM_2_AWPROT;
  input [3:0]AP_AXIMM_2_AWREGION;
  input [3:0]AP_AXIMM_2_AWQOS;
  input AP_AXIMM_2_AWVALID;
  output AP_AXIMM_2_AWREADY;
  input [31:0]AP_AXIMM_2_WDATA;
  input [3:0]AP_AXIMM_2_WSTRB;
  input AP_AXIMM_2_WLAST;
  input AP_AXIMM_2_WVALID;
  output AP_AXIMM_2_WREADY;
  output [1:0]AP_AXIMM_2_BRESP;
  output AP_AXIMM_2_BVALID;
  input AP_AXIMM_2_BREADY;
  input [31:0]AP_AXIMM_2_ARADDR;
  input [7:0]AP_AXIMM_2_ARLEN;
  input [2:0]AP_AXIMM_2_ARSIZE;
  input [1:0]AP_AXIMM_2_ARBURST;
  input [1:0]AP_AXIMM_2_ARLOCK;
  input [3:0]AP_AXIMM_2_ARCACHE;
  input [2:0]AP_AXIMM_2_ARPROT;
  input [3:0]AP_AXIMM_2_ARREGION;
  input [3:0]AP_AXIMM_2_ARQOS;
  input AP_AXIMM_2_ARVALID;
  output AP_AXIMM_2_ARREADY;
  output [31:0]AP_AXIMM_2_RDATA;
  output [1:0]AP_AXIMM_2_RRESP;
  output AP_AXIMM_2_RLAST;
  output AP_AXIMM_2_RVALID;
  input AP_AXIMM_2_RREADY;
  output [31:0]M_AXIMM_2_AWADDR;
  output [7:0]M_AXIMM_2_AWLEN;
  output [2:0]M_AXIMM_2_AWSIZE;
  output [1:0]M_AXIMM_2_AWBURST;
  output [1:0]M_AXIMM_2_AWLOCK;
  output [3:0]M_AXIMM_2_AWCACHE;
  output [2:0]M_AXIMM_2_AWPROT;
  output [3:0]M_AXIMM_2_AWREGION;
  output [3:0]M_AXIMM_2_AWQOS;
  output M_AXIMM_2_AWVALID;
  input M_AXIMM_2_AWREADY;
  output [31:0]M_AXIMM_2_WDATA;
  output [3:0]M_AXIMM_2_WSTRB;
  output M_AXIMM_2_WLAST;
  output M_AXIMM_2_WVALID;
  input M_AXIMM_2_WREADY;
  input [1:0]M_AXIMM_2_BRESP;
  input M_AXIMM_2_BVALID;
  output M_AXIMM_2_BREADY;
  output [31:0]M_AXIMM_2_ARADDR;
  output [7:0]M_AXIMM_2_ARLEN;
  output [2:0]M_AXIMM_2_ARSIZE;
  output [1:0]M_AXIMM_2_ARBURST;
  output [1:0]M_AXIMM_2_ARLOCK;
  output [3:0]M_AXIMM_2_ARCACHE;
  output [2:0]M_AXIMM_2_ARPROT;
  output [3:0]M_AXIMM_2_ARREGION;
  output [3:0]M_AXIMM_2_ARQOS;
  output M_AXIMM_2_ARVALID;
  input M_AXIMM_2_ARREADY;
  input [31:0]M_AXIMM_2_RDATA;
  input [1:0]M_AXIMM_2_RRESP;
  input M_AXIMM_2_RLAST;
  input M_AXIMM_2_RVALID;
  output M_AXIMM_2_RREADY;
  input [31:0]AP_AXIMM_3_AWADDR;
  input [7:0]AP_AXIMM_3_AWLEN;
  input [2:0]AP_AXIMM_3_AWSIZE;
  input [1:0]AP_AXIMM_3_AWBURST;
  input [1:0]AP_AXIMM_3_AWLOCK;
  input [3:0]AP_AXIMM_3_AWCACHE;
  input [2:0]AP_AXIMM_3_AWPROT;
  input [3:0]AP_AXIMM_3_AWREGION;
  input [3:0]AP_AXIMM_3_AWQOS;
  input AP_AXIMM_3_AWVALID;
  output AP_AXIMM_3_AWREADY;
  input [31:0]AP_AXIMM_3_WDATA;
  input [3:0]AP_AXIMM_3_WSTRB;
  input AP_AXIMM_3_WLAST;
  input AP_AXIMM_3_WVALID;
  output AP_AXIMM_3_WREADY;
  output [1:0]AP_AXIMM_3_BRESP;
  output AP_AXIMM_3_BVALID;
  input AP_AXIMM_3_BREADY;
  input [31:0]AP_AXIMM_3_ARADDR;
  input [7:0]AP_AXIMM_3_ARLEN;
  input [2:0]AP_AXIMM_3_ARSIZE;
  input [1:0]AP_AXIMM_3_ARBURST;
  input [1:0]AP_AXIMM_3_ARLOCK;
  input [3:0]AP_AXIMM_3_ARCACHE;
  input [2:0]AP_AXIMM_3_ARPROT;
  input [3:0]AP_AXIMM_3_ARREGION;
  input [3:0]AP_AXIMM_3_ARQOS;
  input AP_AXIMM_3_ARVALID;
  output AP_AXIMM_3_ARREADY;
  output [31:0]AP_AXIMM_3_RDATA;
  output [1:0]AP_AXIMM_3_RRESP;
  output AP_AXIMM_3_RLAST;
  output AP_AXIMM_3_RVALID;
  input AP_AXIMM_3_RREADY;
  output [31:0]M_AXIMM_3_AWADDR;
  output [7:0]M_AXIMM_3_AWLEN;
  output [2:0]M_AXIMM_3_AWSIZE;
  output [1:0]M_AXIMM_3_AWBURST;
  output [1:0]M_AXIMM_3_AWLOCK;
  output [3:0]M_AXIMM_3_AWCACHE;
  output [2:0]M_AXIMM_3_AWPROT;
  output [3:0]M_AXIMM_3_AWREGION;
  output [3:0]M_AXIMM_3_AWQOS;
  output M_AXIMM_3_AWVALID;
  input M_AXIMM_3_AWREADY;
  output [31:0]M_AXIMM_3_WDATA;
  output [3:0]M_AXIMM_3_WSTRB;
  output M_AXIMM_3_WLAST;
  output M_AXIMM_3_WVALID;
  input M_AXIMM_3_WREADY;
  input [1:0]M_AXIMM_3_BRESP;
  input M_AXIMM_3_BVALID;
  output M_AXIMM_3_BREADY;
  output [31:0]M_AXIMM_3_ARADDR;
  output [7:0]M_AXIMM_3_ARLEN;
  output [2:0]M_AXIMM_3_ARSIZE;
  output [1:0]M_AXIMM_3_ARBURST;
  output [1:0]M_AXIMM_3_ARLOCK;
  output [3:0]M_AXIMM_3_ARCACHE;
  output [2:0]M_AXIMM_3_ARPROT;
  output [3:0]M_AXIMM_3_ARREGION;
  output [3:0]M_AXIMM_3_ARQOS;
  output M_AXIMM_3_ARVALID;
  input M_AXIMM_3_ARREADY;
  input [31:0]M_AXIMM_3_RDATA;
  input [1:0]M_AXIMM_3_RRESP;
  input M_AXIMM_3_RLAST;
  input M_AXIMM_3_RVALID;
  output M_AXIMM_3_RREADY;
endmodule
